### ISSUE TITLE
" Invalid Method! "

### ISSUE THREAD

**Issue by lezi1022** [larkjs/lark-router#27]
node:6.6.0
system:mac os

Unhandled rejection AssertionError: Invalid Method!
    at Router.route (/Users/admin/Documents/work/credit/shopserver/node_modules/lark-router/index.js:142:9)
    at Router.load (/Users/admin/Documents/work/credit/shopserver/node_modules/lark-router/index.js:225:26)
    at Router.load (/Users/admin/Documents/work/credit/shopserver/node_modules/lark-router/index.js:236:24)
    at Router.load (/Users/admin/Documents/work/credit/shopserver/node_modules/lark-router/index.js:236:24)
    at confit.create.then.c (/Users/admin/Documents/work/credit/shopserver/base.js:81:29)
    at tryCatcher (/Users/admin/Documents/work/credit/shopserver/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/admin/Documents/work/credit/shopserver/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/admin/Documents/work/credit/shopserver/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/admin/Documents/work/credit/shopserver/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/admin/Documents/work/credit/shopserver/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/admin/Documents/work/credit/shopserver/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/admin/Documents/work/credit/shopserver/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/admin/Documents/work/credit/shopserver/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback](timers.js:533:5)

**Comment by viRingbells** [comment]
load方法已经从Router里面移除了，现在Router只负责路由功能。通过配置或者文件组织结构来配置路由规则的功能现在在[lark-router-config](https://github.com/larkjs/lark-router-config)模块中。对应的BUG应该也已经改好了。
